services:

  mysql:
    image: wow-cmangos-db
    container_name: wow-cmangos-db
    build:
      context: mysql
      dockerfile: Dockerfile-cmangos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./volumes/cmangos_mysql:/var/lib/mysql

  python:
    image: wow-cmangos-python
    container_name: wow-cmangos-python
    build:
      context: python
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_started
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./python:/python
