version: '3.1'

services:

  mysql:
    image: mysql:5.7-debian
    container_name: wow-classic-db
    build:
      context: mysql
      # dockerfile: Dockerfile-cmangos
      dockerfile: Dockerfile-vmangos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PWD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - backend

  python:
    image: python:3.9-slim-bullseye
    container_name: wow-classic-python
    build:
      context: python
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: 
      mysql:
        condition: service_started
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./python:/python
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
