FROM mysql:5.7
LABEL MAINTAINER="Thomas Laurenson <thomas@thomaslaurenson.com>"

# Update system, and install git
RUN apt-get update
RUN apt-get install -y git

# Clone project repos
WORKDIR /opt
RUN git clone --depth=1 https://github.com/cmangos/classic-db.git; exit 0
RUN git clone --depth=1 https://github.com/cmangos/mangos-classic.git; exit 0

# Extract database
WORKDIR /opt/classic-db/Full_DB
RUN gunzip ClassicDB_1_11_z2757.sql.gz; exit 0

# Copy autopopulate script to docker entrypoint to auto insert data
# Comment out if you don't want to auto populate
# COPY ./init_cmangos.sh /docker-entrypoint-initdb.d/init_cmangos.sh
