FROM mysql:8.0-debian

# Update system, and install git
RUN apt-get update
RUN apt-get install -y git

# Clone cmangos/classic-db project database repo
WORKDIR /opt
RUN git clone --depth=1 https://github.com/cmangos/classic-db.git; exit 0

# We also need the core to get the base SQL files
RUN git clone --depth=1 https://github.com/cmangos/mangos-classic.git; exit 0

RUN chown -R mysql:mysql /opt/classic-db
RUN chown -R mysql:mysql /opt/mangos-classic

COPY ./init_cmangos_full.sh /docker-entrypoint-initdb.d/init_cmangos_full.sh

# COPY ./init_cmangos_full.sh /opt/init_cmangos_full.sh
